// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mockrepo

import (
	"context"
	"github.com/google/uuid"
	"github.com/kairosedubf/wobsongo/data"
	"github.com/kairosedubf/wobsongo/dto"
	"github.com/kairosedubf/wobsongo/model"
	"sync"
)

// Ensure, that AtomicKnowledgeRepoerMock does implement data.AtomicKnowledgeRepoer.
// If this is not the case, regenerate this file with moq.
var _ data.AtomicKnowledgeRepoer = &AtomicKnowledgeRepoerMock{}

// AtomicKnowledgeRepoerMock is a mock implementation of data.AtomicKnowledgeRepoer.
//
//	func TestSomethingThatUsesAtomicKnowledgeRepoer(t *testing.T) {
//
//		// make and configure a mocked data.AtomicKnowledgeRepoer
//		mockedAtomicKnowledgeRepoer := &AtomicKnowledgeRepoerMock{
//			CreateBatchFunc: func(ctx context.Context, knowledge []model.AtomicKnowledge) error {
//				panic("mock out the CreateBatch method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*model.AtomicKnowledge, error) {
//				panic("mock out the GetByID method")
//			},
//			ListNeedingEmbeddingFunc: func(ctx context.Context, documentID uuid.UUID) ([]model.AtomicKnowledge, error) {
//				panic("mock out the ListNeedingEmbedding method")
//			},
//			MarkChunkKnowledgeExtractedFunc: func(ctx context.Context, chunkID uuid.UUID) error {
//				panic("mock out the MarkChunkKnowledgeExtracted method")
//			},
//			PaginateByDocumentIDFunc: func(ctx context.Context, documentID uuid.UUID, q data.SupportsPagination) (*dto.PaginationResults[model.AtomicKnowledge], error) {
//				panic("mock out the PaginateByDocumentID method")
//			},
//			SearchByEmbeddingFunc: func(ctx context.Context, queryVector []float32, limit int) ([]data.ScoredResult[model.AtomicKnowledge], error) {
//				panic("mock out the SearchByEmbedding method")
//			},
//			SearchByFullTextFunc: func(ctx context.Context, query string, limit int) ([]data.ScoredResult[model.AtomicKnowledge], error) {
//				panic("mock out the SearchByFullText method")
//			},
//			SearchBySimilarityFunc: func(ctx context.Context, query string, limit int) ([]data.ScoredResult[model.AtomicKnowledge], error) {
//				panic("mock out the SearchBySimilarity method")
//			},
//			UpdateEmbeddingFunc: func(ctx context.Context, id uuid.UUID, embedding []float32) error {
//				panic("mock out the UpdateEmbedding method")
//			},
//			WithTxFunc: func(ctx context.Context, fn func(data.AtomicKnowledgeRepoer) error) error {
//				panic("mock out the WithTx method")
//			},
//		}
//
//		// use mockedAtomicKnowledgeRepoer in code that requires data.AtomicKnowledgeRepoer
//		// and then make assertions.
//
//	}
type AtomicKnowledgeRepoerMock struct {
	// CreateBatchFunc mocks the CreateBatch method.
	CreateBatchFunc func(ctx context.Context, knowledge []model.AtomicKnowledge) error

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*model.AtomicKnowledge, error)

	// ListNeedingEmbeddingFunc mocks the ListNeedingEmbedding method.
	ListNeedingEmbeddingFunc func(ctx context.Context, documentID uuid.UUID) ([]model.AtomicKnowledge, error)

	// MarkChunkKnowledgeExtractedFunc mocks the MarkChunkKnowledgeExtracted method.
	MarkChunkKnowledgeExtractedFunc func(ctx context.Context, chunkID uuid.UUID) error

	// PaginateByDocumentIDFunc mocks the PaginateByDocumentID method.
	PaginateByDocumentIDFunc func(ctx context.Context, documentID uuid.UUID, q data.SupportsPagination) (*dto.PaginationResults[model.AtomicKnowledge], error)

	// SearchByEmbeddingFunc mocks the SearchByEmbedding method.
	SearchByEmbeddingFunc func(ctx context.Context, queryVector []float32, limit int) ([]data.ScoredResult[model.AtomicKnowledge], error)

	// SearchByFullTextFunc mocks the SearchByFullText method.
	SearchByFullTextFunc func(ctx context.Context, query string, limit int) ([]data.ScoredResult[model.AtomicKnowledge], error)

	// SearchBySimilarityFunc mocks the SearchBySimilarity method.
	SearchBySimilarityFunc func(ctx context.Context, query string, limit int) ([]data.ScoredResult[model.AtomicKnowledge], error)

	// UpdateEmbeddingFunc mocks the UpdateEmbedding method.
	UpdateEmbeddingFunc func(ctx context.Context, id uuid.UUID, embedding []float32) error

	// WithTxFunc mocks the WithTx method.
	WithTxFunc func(ctx context.Context, fn func(data.AtomicKnowledgeRepoer) error) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateBatch holds details about calls to the CreateBatch method.
		CreateBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Knowledge is the knowledge argument value.
			Knowledge []model.AtomicKnowledge
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// ListNeedingEmbedding holds details about calls to the ListNeedingEmbedding method.
		ListNeedingEmbedding []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID uuid.UUID
		}
		// MarkChunkKnowledgeExtracted holds details about calls to the MarkChunkKnowledgeExtracted method.
		MarkChunkKnowledgeExtracted []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChunkID is the chunkID argument value.
			ChunkID uuid.UUID
		}
		// PaginateByDocumentID holds details about calls to the PaginateByDocumentID method.
		PaginateByDocumentID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID uuid.UUID
			// Q is the q argument value.
			Q data.SupportsPagination
		}
		// SearchByEmbedding holds details about calls to the SearchByEmbedding method.
		SearchByEmbedding []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// QueryVector is the queryVector argument value.
			QueryVector []float32
			// Limit is the limit argument value.
			Limit int
		}
		// SearchByFullText holds details about calls to the SearchByFullText method.
		SearchByFullText []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// Limit is the limit argument value.
			Limit int
		}
		// SearchBySimilarity holds details about calls to the SearchBySimilarity method.
		SearchBySimilarity []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// Limit is the limit argument value.
			Limit int
		}
		// UpdateEmbedding holds details about calls to the UpdateEmbedding method.
		UpdateEmbedding []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// Embedding is the embedding argument value.
			Embedding []float32
		}
		// WithTx holds details about calls to the WithTx method.
		WithTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fn is the fn argument value.
			Fn func(data.AtomicKnowledgeRepoer) error
		}
	}
	lockCreateBatch                 sync.RWMutex
	lockGetByID                     sync.RWMutex
	lockListNeedingEmbedding        sync.RWMutex
	lockMarkChunkKnowledgeExtracted sync.RWMutex
	lockPaginateByDocumentID        sync.RWMutex
	lockSearchByEmbedding           sync.RWMutex
	lockSearchByFullText            sync.RWMutex
	lockSearchBySimilarity          sync.RWMutex
	lockUpdateEmbedding             sync.RWMutex
	lockWithTx                      sync.RWMutex
}

// CreateBatch calls CreateBatchFunc.
func (mock *AtomicKnowledgeRepoerMock) CreateBatch(ctx context.Context, knowledge []model.AtomicKnowledge) error {
	if mock.CreateBatchFunc == nil {
		panic("AtomicKnowledgeRepoerMock.CreateBatchFunc: method is nil but AtomicKnowledgeRepoer.CreateBatch was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Knowledge []model.AtomicKnowledge
	}{
		Ctx:       ctx,
		Knowledge: knowledge,
	}
	mock.lockCreateBatch.Lock()
	mock.calls.CreateBatch = append(mock.calls.CreateBatch, callInfo)
	mock.lockCreateBatch.Unlock()
	return mock.CreateBatchFunc(ctx, knowledge)
}

// CreateBatchCalls gets all the calls that were made to CreateBatch.
// Check the length with:
//
//	len(mockedAtomicKnowledgeRepoer.CreateBatchCalls())
func (mock *AtomicKnowledgeRepoerMock) CreateBatchCalls() []struct {
	Ctx       context.Context
	Knowledge []model.AtomicKnowledge
} {
	var calls []struct {
		Ctx       context.Context
		Knowledge []model.AtomicKnowledge
	}
	mock.lockCreateBatch.RLock()
	calls = mock.calls.CreateBatch
	mock.lockCreateBatch.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *AtomicKnowledgeRepoerMock) GetByID(ctx context.Context, id uuid.UUID) (*model.AtomicKnowledge, error) {
	if mock.GetByIDFunc == nil {
		panic("AtomicKnowledgeRepoerMock.GetByIDFunc: method is nil but AtomicKnowledgeRepoer.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedAtomicKnowledgeRepoer.GetByIDCalls())
func (mock *AtomicKnowledgeRepoerMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// ListNeedingEmbedding calls ListNeedingEmbeddingFunc.
func (mock *AtomicKnowledgeRepoerMock) ListNeedingEmbedding(ctx context.Context, documentID uuid.UUID) ([]model.AtomicKnowledge, error) {
	if mock.ListNeedingEmbeddingFunc == nil {
		panic("AtomicKnowledgeRepoerMock.ListNeedingEmbeddingFunc: method is nil but AtomicKnowledgeRepoer.ListNeedingEmbedding was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		DocumentID uuid.UUID
	}{
		Ctx:        ctx,
		DocumentID: documentID,
	}
	mock.lockListNeedingEmbedding.Lock()
	mock.calls.ListNeedingEmbedding = append(mock.calls.ListNeedingEmbedding, callInfo)
	mock.lockListNeedingEmbedding.Unlock()
	return mock.ListNeedingEmbeddingFunc(ctx, documentID)
}

// ListNeedingEmbeddingCalls gets all the calls that were made to ListNeedingEmbedding.
// Check the length with:
//
//	len(mockedAtomicKnowledgeRepoer.ListNeedingEmbeddingCalls())
func (mock *AtomicKnowledgeRepoerMock) ListNeedingEmbeddingCalls() []struct {
	Ctx        context.Context
	DocumentID uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		DocumentID uuid.UUID
	}
	mock.lockListNeedingEmbedding.RLock()
	calls = mock.calls.ListNeedingEmbedding
	mock.lockListNeedingEmbedding.RUnlock()
	return calls
}

// MarkChunkKnowledgeExtracted calls MarkChunkKnowledgeExtractedFunc.
func (mock *AtomicKnowledgeRepoerMock) MarkChunkKnowledgeExtracted(ctx context.Context, chunkID uuid.UUID) error {
	if mock.MarkChunkKnowledgeExtractedFunc == nil {
		panic("AtomicKnowledgeRepoerMock.MarkChunkKnowledgeExtractedFunc: method is nil but AtomicKnowledgeRepoer.MarkChunkKnowledgeExtracted was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ChunkID uuid.UUID
	}{
		Ctx:     ctx,
		ChunkID: chunkID,
	}
	mock.lockMarkChunkKnowledgeExtracted.Lock()
	mock.calls.MarkChunkKnowledgeExtracted = append(mock.calls.MarkChunkKnowledgeExtracted, callInfo)
	mock.lockMarkChunkKnowledgeExtracted.Unlock()
	return mock.MarkChunkKnowledgeExtractedFunc(ctx, chunkID)
}

// MarkChunkKnowledgeExtractedCalls gets all the calls that were made to MarkChunkKnowledgeExtracted.
// Check the length with:
//
//	len(mockedAtomicKnowledgeRepoer.MarkChunkKnowledgeExtractedCalls())
func (mock *AtomicKnowledgeRepoerMock) MarkChunkKnowledgeExtractedCalls() []struct {
	Ctx     context.Context
	ChunkID uuid.UUID
} {
	var calls []struct {
		Ctx     context.Context
		ChunkID uuid.UUID
	}
	mock.lockMarkChunkKnowledgeExtracted.RLock()
	calls = mock.calls.MarkChunkKnowledgeExtracted
	mock.lockMarkChunkKnowledgeExtracted.RUnlock()
	return calls
}

// PaginateByDocumentID calls PaginateByDocumentIDFunc.
func (mock *AtomicKnowledgeRepoerMock) PaginateByDocumentID(ctx context.Context, documentID uuid.UUID, q data.SupportsPagination) (*dto.PaginationResults[model.AtomicKnowledge], error) {
	if mock.PaginateByDocumentIDFunc == nil {
		panic("AtomicKnowledgeRepoerMock.PaginateByDocumentIDFunc: method is nil but AtomicKnowledgeRepoer.PaginateByDocumentID was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		DocumentID uuid.UUID
		Q          data.SupportsPagination
	}{
		Ctx:        ctx,
		DocumentID: documentID,
		Q:          q,
	}
	mock.lockPaginateByDocumentID.Lock()
	mock.calls.PaginateByDocumentID = append(mock.calls.PaginateByDocumentID, callInfo)
	mock.lockPaginateByDocumentID.Unlock()
	return mock.PaginateByDocumentIDFunc(ctx, documentID, q)
}

// PaginateByDocumentIDCalls gets all the calls that were made to PaginateByDocumentID.
// Check the length with:
//
//	len(mockedAtomicKnowledgeRepoer.PaginateByDocumentIDCalls())
func (mock *AtomicKnowledgeRepoerMock) PaginateByDocumentIDCalls() []struct {
	Ctx        context.Context
	DocumentID uuid.UUID
	Q          data.SupportsPagination
} {
	var calls []struct {
		Ctx        context.Context
		DocumentID uuid.UUID
		Q          data.SupportsPagination
	}
	mock.lockPaginateByDocumentID.RLock()
	calls = mock.calls.PaginateByDocumentID
	mock.lockPaginateByDocumentID.RUnlock()
	return calls
}

// SearchByEmbedding calls SearchByEmbeddingFunc.
func (mock *AtomicKnowledgeRepoerMock) SearchByEmbedding(ctx context.Context, queryVector []float32, limit int) ([]data.ScoredResult[model.AtomicKnowledge], error) {
	if mock.SearchByEmbeddingFunc == nil {
		panic("AtomicKnowledgeRepoerMock.SearchByEmbeddingFunc: method is nil but AtomicKnowledgeRepoer.SearchByEmbedding was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		QueryVector []float32
		Limit       int
	}{
		Ctx:         ctx,
		QueryVector: queryVector,
		Limit:       limit,
	}
	mock.lockSearchByEmbedding.Lock()
	mock.calls.SearchByEmbedding = append(mock.calls.SearchByEmbedding, callInfo)
	mock.lockSearchByEmbedding.Unlock()
	return mock.SearchByEmbeddingFunc(ctx, queryVector, limit)
}

// SearchByEmbeddingCalls gets all the calls that were made to SearchByEmbedding.
// Check the length with:
//
//	len(mockedAtomicKnowledgeRepoer.SearchByEmbeddingCalls())
func (mock *AtomicKnowledgeRepoerMock) SearchByEmbeddingCalls() []struct {
	Ctx         context.Context
	QueryVector []float32
	Limit       int
} {
	var calls []struct {
		Ctx         context.Context
		QueryVector []float32
		Limit       int
	}
	mock.lockSearchByEmbedding.RLock()
	calls = mock.calls.SearchByEmbedding
	mock.lockSearchByEmbedding.RUnlock()
	return calls
}

// SearchByFullText calls SearchByFullTextFunc.
func (mock *AtomicKnowledgeRepoerMock) SearchByFullText(ctx context.Context, query string, limit int) ([]data.ScoredResult[model.AtomicKnowledge], error) {
	if mock.SearchByFullTextFunc == nil {
		panic("AtomicKnowledgeRepoerMock.SearchByFullTextFunc: method is nil but AtomicKnowledgeRepoer.SearchByFullText was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
		Limit int
	}{
		Ctx:   ctx,
		Query: query,
		Limit: limit,
	}
	mock.lockSearchByFullText.Lock()
	mock.calls.SearchByFullText = append(mock.calls.SearchByFullText, callInfo)
	mock.lockSearchByFullText.Unlock()
	return mock.SearchByFullTextFunc(ctx, query, limit)
}

// SearchByFullTextCalls gets all the calls that were made to SearchByFullText.
// Check the length with:
//
//	len(mockedAtomicKnowledgeRepoer.SearchByFullTextCalls())
func (mock *AtomicKnowledgeRepoerMock) SearchByFullTextCalls() []struct {
	Ctx   context.Context
	Query string
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Query string
		Limit int
	}
	mock.lockSearchByFullText.RLock()
	calls = mock.calls.SearchByFullText
	mock.lockSearchByFullText.RUnlock()
	return calls
}

// SearchBySimilarity calls SearchBySimilarityFunc.
func (mock *AtomicKnowledgeRepoerMock) SearchBySimilarity(ctx context.Context, query string, limit int) ([]data.ScoredResult[model.AtomicKnowledge], error) {
	if mock.SearchBySimilarityFunc == nil {
		panic("AtomicKnowledgeRepoerMock.SearchBySimilarityFunc: method is nil but AtomicKnowledgeRepoer.SearchBySimilarity was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
		Limit int
	}{
		Ctx:   ctx,
		Query: query,
		Limit: limit,
	}
	mock.lockSearchBySimilarity.Lock()
	mock.calls.SearchBySimilarity = append(mock.calls.SearchBySimilarity, callInfo)
	mock.lockSearchBySimilarity.Unlock()
	return mock.SearchBySimilarityFunc(ctx, query, limit)
}

// SearchBySimilarityCalls gets all the calls that were made to SearchBySimilarity.
// Check the length with:
//
//	len(mockedAtomicKnowledgeRepoer.SearchBySimilarityCalls())
func (mock *AtomicKnowledgeRepoerMock) SearchBySimilarityCalls() []struct {
	Ctx   context.Context
	Query string
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Query string
		Limit int
	}
	mock.lockSearchBySimilarity.RLock()
	calls = mock.calls.SearchBySimilarity
	mock.lockSearchBySimilarity.RUnlock()
	return calls
}

// UpdateEmbedding calls UpdateEmbeddingFunc.
func (mock *AtomicKnowledgeRepoerMock) UpdateEmbedding(ctx context.Context, id uuid.UUID, embedding []float32) error {
	if mock.UpdateEmbeddingFunc == nil {
		panic("AtomicKnowledgeRepoerMock.UpdateEmbeddingFunc: method is nil but AtomicKnowledgeRepoer.UpdateEmbedding was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ID        uuid.UUID
		Embedding []float32
	}{
		Ctx:       ctx,
		ID:        id,
		Embedding: embedding,
	}
	mock.lockUpdateEmbedding.Lock()
	mock.calls.UpdateEmbedding = append(mock.calls.UpdateEmbedding, callInfo)
	mock.lockUpdateEmbedding.Unlock()
	return mock.UpdateEmbeddingFunc(ctx, id, embedding)
}

// UpdateEmbeddingCalls gets all the calls that were made to UpdateEmbedding.
// Check the length with:
//
//	len(mockedAtomicKnowledgeRepoer.UpdateEmbeddingCalls())
func (mock *AtomicKnowledgeRepoerMock) UpdateEmbeddingCalls() []struct {
	Ctx       context.Context
	ID        uuid.UUID
	Embedding []float32
} {
	var calls []struct {
		Ctx       context.Context
		ID        uuid.UUID
		Embedding []float32
	}
	mock.lockUpdateEmbedding.RLock()
	calls = mock.calls.UpdateEmbedding
	mock.lockUpdateEmbedding.RUnlock()
	return calls
}

// WithTx calls WithTxFunc.
func (mock *AtomicKnowledgeRepoerMock) WithTx(ctx context.Context, fn func(data.AtomicKnowledgeRepoer) error) error {
	if mock.WithTxFunc == nil {
		panic("AtomicKnowledgeRepoerMock.WithTxFunc: method is nil but AtomicKnowledgeRepoer.WithTx was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Fn  func(data.AtomicKnowledgeRepoer) error
	}{
		Ctx: ctx,
		Fn:  fn,
	}
	mock.lockWithTx.Lock()
	mock.calls.WithTx = append(mock.calls.WithTx, callInfo)
	mock.lockWithTx.Unlock()
	return mock.WithTxFunc(ctx, fn)
}

// WithTxCalls gets all the calls that were made to WithTx.
// Check the length with:
//
//	len(mockedAtomicKnowledgeRepoer.WithTxCalls())
func (mock *AtomicKnowledgeRepoerMock) WithTxCalls() []struct {
	Ctx context.Context
	Fn  func(data.AtomicKnowledgeRepoer) error
} {
	var calls []struct {
		Ctx context.Context
		Fn  func(data.AtomicKnowledgeRepoer) error
	}
	mock.lockWithTx.RLock()
	calls = mock.calls.WithTx
	mock.lockWithTx.RUnlock()
	return calls
}
