// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mockrepo

import (
	"context"
	"github.com/google/uuid"
	"github.com/kairosedubf/wobsongo/data"
	"github.com/kairosedubf/wobsongo/model"
	"github.com/kairosedubf/wobsongo/queue"
	"sync"
)

// Ensure, that DocumentChunkRepoerMock does implement data.DocumentChunkRepoer.
// If this is not the case, regenerate this file with moq.
var _ data.DocumentChunkRepoer = &DocumentChunkRepoerMock{}

// DocumentChunkRepoerMock is a mock implementation of data.DocumentChunkRepoer.
//
//	func TestSomethingThatUsesDocumentChunkRepoer(t *testing.T) {
//
//		// make and configure a mocked data.DocumentChunkRepoer
//		mockedDocumentChunkRepoer := &DocumentChunkRepoerMock{
//			CreateBatchFunc: func(ctx context.Context, chunks []model.DocumentChunk) error {
//				panic("mock out the CreateBatch method")
//			},
//			EnqueueFunc: func(ctx context.Context, payload queue.BackgroundJob) error {
//				panic("mock out the Enqueue method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*model.DocumentChunk, error) {
//				panic("mock out the GetByID method")
//			},
//			ListByDocumentIDFunc: func(ctx context.Context, documentID uuid.UUID) ([]model.DocumentChunk, error) {
//				panic("mock out the ListByDocumentID method")
//			},
//			ListByDocumentIDAndPageFunc: func(ctx context.Context, documentID uuid.UUID, page int) ([]model.DocumentChunk, error) {
//				panic("mock out the ListByDocumentIDAndPage method")
//			},
//			ListChunksNeedingEmbeddingFunc: func(ctx context.Context, documentID uuid.UUID) ([]model.DocumentChunk, error) {
//				panic("mock out the ListChunksNeedingEmbedding method")
//			},
//			ListChunksNeedingKnowledgeExtractionFunc: func(ctx context.Context, documentID uuid.UUID) ([]model.DocumentChunk, error) {
//				panic("mock out the ListChunksNeedingKnowledgeExtraction method")
//			},
//			ListChunksNeedingTranslationFunc: func(ctx context.Context, documentID uuid.UUID) ([]model.DocumentChunk, error) {
//				panic("mock out the ListChunksNeedingTranslation method")
//			},
//			ListDocumentIDsNeedingTranslationFunc: func(ctx context.Context) ([]uuid.UUID, error) {
//				panic("mock out the ListDocumentIDsNeedingTranslation method")
//			},
//			SearchByEmbeddingFunc: func(ctx context.Context, queryVector []float32, limit int) ([]data.ScoredResult[model.DocumentChunk], error) {
//				panic("mock out the SearchByEmbedding method")
//			},
//			SearchByFullTextFunc: func(ctx context.Context, query string, limit int) ([]data.ScoredResult[model.DocumentChunk], error) {
//				panic("mock out the SearchByFullText method")
//			},
//			ShouldBeStoredFunc: func(ctx context.Context, doc model.Document, chunk model.DocumentChunk) (bool, error) {
//				panic("mock out the ShouldBeStored method")
//			},
//			UpdateFunc: func(ctx context.Context, chunk *model.DocumentChunk) error {
//				panic("mock out the Update method")
//			},
//			UpdateChunkTranslationFunc: func(ctx context.Context, chunkID uuid.UUID, textTranslated string) error {
//				panic("mock out the UpdateChunkTranslation method")
//			},
//			WithTxFunc: func(ctx context.Context, fn func(data.DocumentChunkRepoer) error) error {
//				panic("mock out the WithTx method")
//			},
//		}
//
//		// use mockedDocumentChunkRepoer in code that requires data.DocumentChunkRepoer
//		// and then make assertions.
//
//	}
type DocumentChunkRepoerMock struct {
	// CreateBatchFunc mocks the CreateBatch method.
	CreateBatchFunc func(ctx context.Context, chunks []model.DocumentChunk) error

	// EnqueueFunc mocks the Enqueue method.
	EnqueueFunc func(ctx context.Context, payload queue.BackgroundJob) error

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*model.DocumentChunk, error)

	// ListByDocumentIDFunc mocks the ListByDocumentID method.
	ListByDocumentIDFunc func(ctx context.Context, documentID uuid.UUID) ([]model.DocumentChunk, error)

	// ListByDocumentIDAndPageFunc mocks the ListByDocumentIDAndPage method.
	ListByDocumentIDAndPageFunc func(ctx context.Context, documentID uuid.UUID, page int) ([]model.DocumentChunk, error)

	// ListChunksNeedingEmbeddingFunc mocks the ListChunksNeedingEmbedding method.
	ListChunksNeedingEmbeddingFunc func(ctx context.Context, documentID uuid.UUID) ([]model.DocumentChunk, error)

	// ListChunksNeedingKnowledgeExtractionFunc mocks the ListChunksNeedingKnowledgeExtraction method.
	ListChunksNeedingKnowledgeExtractionFunc func(ctx context.Context, documentID uuid.UUID) ([]model.DocumentChunk, error)

	// ListChunksNeedingTranslationFunc mocks the ListChunksNeedingTranslation method.
	ListChunksNeedingTranslationFunc func(ctx context.Context, documentID uuid.UUID) ([]model.DocumentChunk, error)

	// ListDocumentIDsNeedingTranslationFunc mocks the ListDocumentIDsNeedingTranslation method.
	ListDocumentIDsNeedingTranslationFunc func(ctx context.Context) ([]uuid.UUID, error)

	// SearchByEmbeddingFunc mocks the SearchByEmbedding method.
	SearchByEmbeddingFunc func(ctx context.Context, queryVector []float32, limit int) ([]data.ScoredResult[model.DocumentChunk], error)

	// SearchByFullTextFunc mocks the SearchByFullText method.
	SearchByFullTextFunc func(ctx context.Context, query string, limit int) ([]data.ScoredResult[model.DocumentChunk], error)

	// ShouldBeStoredFunc mocks the ShouldBeStored method.
	ShouldBeStoredFunc func(ctx context.Context, doc model.Document, chunk model.DocumentChunk) (bool, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, chunk *model.DocumentChunk) error

	// UpdateChunkTranslationFunc mocks the UpdateChunkTranslation method.
	UpdateChunkTranslationFunc func(ctx context.Context, chunkID uuid.UUID, textTranslated string) error

	// WithTxFunc mocks the WithTx method.
	WithTxFunc func(ctx context.Context, fn func(data.DocumentChunkRepoer) error) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateBatch holds details about calls to the CreateBatch method.
		CreateBatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Chunks is the chunks argument value.
			Chunks []model.DocumentChunk
		}
		// Enqueue holds details about calls to the Enqueue method.
		Enqueue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Payload is the payload argument value.
			Payload queue.BackgroundJob
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// ListByDocumentID holds details about calls to the ListByDocumentID method.
		ListByDocumentID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID uuid.UUID
		}
		// ListByDocumentIDAndPage holds details about calls to the ListByDocumentIDAndPage method.
		ListByDocumentIDAndPage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID uuid.UUID
			// Page is the page argument value.
			Page int
		}
		// ListChunksNeedingEmbedding holds details about calls to the ListChunksNeedingEmbedding method.
		ListChunksNeedingEmbedding []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID uuid.UUID
		}
		// ListChunksNeedingKnowledgeExtraction holds details about calls to the ListChunksNeedingKnowledgeExtraction method.
		ListChunksNeedingKnowledgeExtraction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID uuid.UUID
		}
		// ListChunksNeedingTranslation holds details about calls to the ListChunksNeedingTranslation method.
		ListChunksNeedingTranslation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DocumentID is the documentID argument value.
			DocumentID uuid.UUID
		}
		// ListDocumentIDsNeedingTranslation holds details about calls to the ListDocumentIDsNeedingTranslation method.
		ListDocumentIDsNeedingTranslation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// SearchByEmbedding holds details about calls to the SearchByEmbedding method.
		SearchByEmbedding []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// QueryVector is the queryVector argument value.
			QueryVector []float32
			// Limit is the limit argument value.
			Limit int
		}
		// SearchByFullText holds details about calls to the SearchByFullText method.
		SearchByFullText []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// Limit is the limit argument value.
			Limit int
		}
		// ShouldBeStored holds details about calls to the ShouldBeStored method.
		ShouldBeStored []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Doc is the doc argument value.
			Doc model.Document
			// Chunk is the chunk argument value.
			Chunk model.DocumentChunk
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Chunk is the chunk argument value.
			Chunk *model.DocumentChunk
		}
		// UpdateChunkTranslation holds details about calls to the UpdateChunkTranslation method.
		UpdateChunkTranslation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChunkID is the chunkID argument value.
			ChunkID uuid.UUID
			// TextTranslated is the textTranslated argument value.
			TextTranslated string
		}
		// WithTx holds details about calls to the WithTx method.
		WithTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fn is the fn argument value.
			Fn func(data.DocumentChunkRepoer) error
		}
	}
	lockCreateBatch                          sync.RWMutex
	lockEnqueue                              sync.RWMutex
	lockGetByID                              sync.RWMutex
	lockListByDocumentID                     sync.RWMutex
	lockListByDocumentIDAndPage              sync.RWMutex
	lockListChunksNeedingEmbedding           sync.RWMutex
	lockListChunksNeedingKnowledgeExtraction sync.RWMutex
	lockListChunksNeedingTranslation         sync.RWMutex
	lockListDocumentIDsNeedingTranslation    sync.RWMutex
	lockSearchByEmbedding                    sync.RWMutex
	lockSearchByFullText                     sync.RWMutex
	lockShouldBeStored                       sync.RWMutex
	lockUpdate                               sync.RWMutex
	lockUpdateChunkTranslation               sync.RWMutex
	lockWithTx                               sync.RWMutex
}

// CreateBatch calls CreateBatchFunc.
func (mock *DocumentChunkRepoerMock) CreateBatch(ctx context.Context, chunks []model.DocumentChunk) error {
	if mock.CreateBatchFunc == nil {
		panic("DocumentChunkRepoerMock.CreateBatchFunc: method is nil but DocumentChunkRepoer.CreateBatch was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Chunks []model.DocumentChunk
	}{
		Ctx:    ctx,
		Chunks: chunks,
	}
	mock.lockCreateBatch.Lock()
	mock.calls.CreateBatch = append(mock.calls.CreateBatch, callInfo)
	mock.lockCreateBatch.Unlock()
	return mock.CreateBatchFunc(ctx, chunks)
}

// CreateBatchCalls gets all the calls that were made to CreateBatch.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.CreateBatchCalls())
func (mock *DocumentChunkRepoerMock) CreateBatchCalls() []struct {
	Ctx    context.Context
	Chunks []model.DocumentChunk
} {
	var calls []struct {
		Ctx    context.Context
		Chunks []model.DocumentChunk
	}
	mock.lockCreateBatch.RLock()
	calls = mock.calls.CreateBatch
	mock.lockCreateBatch.RUnlock()
	return calls
}

// Enqueue calls EnqueueFunc.
func (mock *DocumentChunkRepoerMock) Enqueue(ctx context.Context, payload queue.BackgroundJob) error {
	if mock.EnqueueFunc == nil {
		panic("DocumentChunkRepoerMock.EnqueueFunc: method is nil but DocumentChunkRepoer.Enqueue was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Payload queue.BackgroundJob
	}{
		Ctx:     ctx,
		Payload: payload,
	}
	mock.lockEnqueue.Lock()
	mock.calls.Enqueue = append(mock.calls.Enqueue, callInfo)
	mock.lockEnqueue.Unlock()
	return mock.EnqueueFunc(ctx, payload)
}

// EnqueueCalls gets all the calls that were made to Enqueue.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.EnqueueCalls())
func (mock *DocumentChunkRepoerMock) EnqueueCalls() []struct {
	Ctx     context.Context
	Payload queue.BackgroundJob
} {
	var calls []struct {
		Ctx     context.Context
		Payload queue.BackgroundJob
	}
	mock.lockEnqueue.RLock()
	calls = mock.calls.Enqueue
	mock.lockEnqueue.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *DocumentChunkRepoerMock) GetByID(ctx context.Context, id uuid.UUID) (*model.DocumentChunk, error) {
	if mock.GetByIDFunc == nil {
		panic("DocumentChunkRepoerMock.GetByIDFunc: method is nil but DocumentChunkRepoer.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.GetByIDCalls())
func (mock *DocumentChunkRepoerMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// ListByDocumentID calls ListByDocumentIDFunc.
func (mock *DocumentChunkRepoerMock) ListByDocumentID(ctx context.Context, documentID uuid.UUID) ([]model.DocumentChunk, error) {
	if mock.ListByDocumentIDFunc == nil {
		panic("DocumentChunkRepoerMock.ListByDocumentIDFunc: method is nil but DocumentChunkRepoer.ListByDocumentID was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		DocumentID uuid.UUID
	}{
		Ctx:        ctx,
		DocumentID: documentID,
	}
	mock.lockListByDocumentID.Lock()
	mock.calls.ListByDocumentID = append(mock.calls.ListByDocumentID, callInfo)
	mock.lockListByDocumentID.Unlock()
	return mock.ListByDocumentIDFunc(ctx, documentID)
}

// ListByDocumentIDCalls gets all the calls that were made to ListByDocumentID.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.ListByDocumentIDCalls())
func (mock *DocumentChunkRepoerMock) ListByDocumentIDCalls() []struct {
	Ctx        context.Context
	DocumentID uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		DocumentID uuid.UUID
	}
	mock.lockListByDocumentID.RLock()
	calls = mock.calls.ListByDocumentID
	mock.lockListByDocumentID.RUnlock()
	return calls
}

// ListByDocumentIDAndPage calls ListByDocumentIDAndPageFunc.
func (mock *DocumentChunkRepoerMock) ListByDocumentIDAndPage(ctx context.Context, documentID uuid.UUID, page int) ([]model.DocumentChunk, error) {
	if mock.ListByDocumentIDAndPageFunc == nil {
		panic("DocumentChunkRepoerMock.ListByDocumentIDAndPageFunc: method is nil but DocumentChunkRepoer.ListByDocumentIDAndPage was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		DocumentID uuid.UUID
		Page       int
	}{
		Ctx:        ctx,
		DocumentID: documentID,
		Page:       page,
	}
	mock.lockListByDocumentIDAndPage.Lock()
	mock.calls.ListByDocumentIDAndPage = append(mock.calls.ListByDocumentIDAndPage, callInfo)
	mock.lockListByDocumentIDAndPage.Unlock()
	return mock.ListByDocumentIDAndPageFunc(ctx, documentID, page)
}

// ListByDocumentIDAndPageCalls gets all the calls that were made to ListByDocumentIDAndPage.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.ListByDocumentIDAndPageCalls())
func (mock *DocumentChunkRepoerMock) ListByDocumentIDAndPageCalls() []struct {
	Ctx        context.Context
	DocumentID uuid.UUID
	Page       int
} {
	var calls []struct {
		Ctx        context.Context
		DocumentID uuid.UUID
		Page       int
	}
	mock.lockListByDocumentIDAndPage.RLock()
	calls = mock.calls.ListByDocumentIDAndPage
	mock.lockListByDocumentIDAndPage.RUnlock()
	return calls
}

// ListChunksNeedingEmbedding calls ListChunksNeedingEmbeddingFunc.
func (mock *DocumentChunkRepoerMock) ListChunksNeedingEmbedding(ctx context.Context, documentID uuid.UUID) ([]model.DocumentChunk, error) {
	if mock.ListChunksNeedingEmbeddingFunc == nil {
		panic("DocumentChunkRepoerMock.ListChunksNeedingEmbeddingFunc: method is nil but DocumentChunkRepoer.ListChunksNeedingEmbedding was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		DocumentID uuid.UUID
	}{
		Ctx:        ctx,
		DocumentID: documentID,
	}
	mock.lockListChunksNeedingEmbedding.Lock()
	mock.calls.ListChunksNeedingEmbedding = append(mock.calls.ListChunksNeedingEmbedding, callInfo)
	mock.lockListChunksNeedingEmbedding.Unlock()
	return mock.ListChunksNeedingEmbeddingFunc(ctx, documentID)
}

// ListChunksNeedingEmbeddingCalls gets all the calls that were made to ListChunksNeedingEmbedding.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.ListChunksNeedingEmbeddingCalls())
func (mock *DocumentChunkRepoerMock) ListChunksNeedingEmbeddingCalls() []struct {
	Ctx        context.Context
	DocumentID uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		DocumentID uuid.UUID
	}
	mock.lockListChunksNeedingEmbedding.RLock()
	calls = mock.calls.ListChunksNeedingEmbedding
	mock.lockListChunksNeedingEmbedding.RUnlock()
	return calls
}

// ListChunksNeedingKnowledgeExtraction calls ListChunksNeedingKnowledgeExtractionFunc.
func (mock *DocumentChunkRepoerMock) ListChunksNeedingKnowledgeExtraction(ctx context.Context, documentID uuid.UUID) ([]model.DocumentChunk, error) {
	if mock.ListChunksNeedingKnowledgeExtractionFunc == nil {
		panic("DocumentChunkRepoerMock.ListChunksNeedingKnowledgeExtractionFunc: method is nil but DocumentChunkRepoer.ListChunksNeedingKnowledgeExtraction was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		DocumentID uuid.UUID
	}{
		Ctx:        ctx,
		DocumentID: documentID,
	}
	mock.lockListChunksNeedingKnowledgeExtraction.Lock()
	mock.calls.ListChunksNeedingKnowledgeExtraction = append(mock.calls.ListChunksNeedingKnowledgeExtraction, callInfo)
	mock.lockListChunksNeedingKnowledgeExtraction.Unlock()
	return mock.ListChunksNeedingKnowledgeExtractionFunc(ctx, documentID)
}

// ListChunksNeedingKnowledgeExtractionCalls gets all the calls that were made to ListChunksNeedingKnowledgeExtraction.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.ListChunksNeedingKnowledgeExtractionCalls())
func (mock *DocumentChunkRepoerMock) ListChunksNeedingKnowledgeExtractionCalls() []struct {
	Ctx        context.Context
	DocumentID uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		DocumentID uuid.UUID
	}
	mock.lockListChunksNeedingKnowledgeExtraction.RLock()
	calls = mock.calls.ListChunksNeedingKnowledgeExtraction
	mock.lockListChunksNeedingKnowledgeExtraction.RUnlock()
	return calls
}

// ListChunksNeedingTranslation calls ListChunksNeedingTranslationFunc.
func (mock *DocumentChunkRepoerMock) ListChunksNeedingTranslation(ctx context.Context, documentID uuid.UUID) ([]model.DocumentChunk, error) {
	if mock.ListChunksNeedingTranslationFunc == nil {
		panic("DocumentChunkRepoerMock.ListChunksNeedingTranslationFunc: method is nil but DocumentChunkRepoer.ListChunksNeedingTranslation was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		DocumentID uuid.UUID
	}{
		Ctx:        ctx,
		DocumentID: documentID,
	}
	mock.lockListChunksNeedingTranslation.Lock()
	mock.calls.ListChunksNeedingTranslation = append(mock.calls.ListChunksNeedingTranslation, callInfo)
	mock.lockListChunksNeedingTranslation.Unlock()
	return mock.ListChunksNeedingTranslationFunc(ctx, documentID)
}

// ListChunksNeedingTranslationCalls gets all the calls that were made to ListChunksNeedingTranslation.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.ListChunksNeedingTranslationCalls())
func (mock *DocumentChunkRepoerMock) ListChunksNeedingTranslationCalls() []struct {
	Ctx        context.Context
	DocumentID uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		DocumentID uuid.UUID
	}
	mock.lockListChunksNeedingTranslation.RLock()
	calls = mock.calls.ListChunksNeedingTranslation
	mock.lockListChunksNeedingTranslation.RUnlock()
	return calls
}

// ListDocumentIDsNeedingTranslation calls ListDocumentIDsNeedingTranslationFunc.
func (mock *DocumentChunkRepoerMock) ListDocumentIDsNeedingTranslation(ctx context.Context) ([]uuid.UUID, error) {
	if mock.ListDocumentIDsNeedingTranslationFunc == nil {
		panic("DocumentChunkRepoerMock.ListDocumentIDsNeedingTranslationFunc: method is nil but DocumentChunkRepoer.ListDocumentIDsNeedingTranslation was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListDocumentIDsNeedingTranslation.Lock()
	mock.calls.ListDocumentIDsNeedingTranslation = append(mock.calls.ListDocumentIDsNeedingTranslation, callInfo)
	mock.lockListDocumentIDsNeedingTranslation.Unlock()
	return mock.ListDocumentIDsNeedingTranslationFunc(ctx)
}

// ListDocumentIDsNeedingTranslationCalls gets all the calls that were made to ListDocumentIDsNeedingTranslation.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.ListDocumentIDsNeedingTranslationCalls())
func (mock *DocumentChunkRepoerMock) ListDocumentIDsNeedingTranslationCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListDocumentIDsNeedingTranslation.RLock()
	calls = mock.calls.ListDocumentIDsNeedingTranslation
	mock.lockListDocumentIDsNeedingTranslation.RUnlock()
	return calls
}

// SearchByEmbedding calls SearchByEmbeddingFunc.
func (mock *DocumentChunkRepoerMock) SearchByEmbedding(ctx context.Context, queryVector []float32, limit int) ([]data.ScoredResult[model.DocumentChunk], error) {
	if mock.SearchByEmbeddingFunc == nil {
		panic("DocumentChunkRepoerMock.SearchByEmbeddingFunc: method is nil but DocumentChunkRepoer.SearchByEmbedding was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		QueryVector []float32
		Limit       int
	}{
		Ctx:         ctx,
		QueryVector: queryVector,
		Limit:       limit,
	}
	mock.lockSearchByEmbedding.Lock()
	mock.calls.SearchByEmbedding = append(mock.calls.SearchByEmbedding, callInfo)
	mock.lockSearchByEmbedding.Unlock()
	return mock.SearchByEmbeddingFunc(ctx, queryVector, limit)
}

// SearchByEmbeddingCalls gets all the calls that were made to SearchByEmbedding.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.SearchByEmbeddingCalls())
func (mock *DocumentChunkRepoerMock) SearchByEmbeddingCalls() []struct {
	Ctx         context.Context
	QueryVector []float32
	Limit       int
} {
	var calls []struct {
		Ctx         context.Context
		QueryVector []float32
		Limit       int
	}
	mock.lockSearchByEmbedding.RLock()
	calls = mock.calls.SearchByEmbedding
	mock.lockSearchByEmbedding.RUnlock()
	return calls
}

// SearchByFullText calls SearchByFullTextFunc.
func (mock *DocumentChunkRepoerMock) SearchByFullText(ctx context.Context, query string, limit int) ([]data.ScoredResult[model.DocumentChunk], error) {
	if mock.SearchByFullTextFunc == nil {
		panic("DocumentChunkRepoerMock.SearchByFullTextFunc: method is nil but DocumentChunkRepoer.SearchByFullText was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
		Limit int
	}{
		Ctx:   ctx,
		Query: query,
		Limit: limit,
	}
	mock.lockSearchByFullText.Lock()
	mock.calls.SearchByFullText = append(mock.calls.SearchByFullText, callInfo)
	mock.lockSearchByFullText.Unlock()
	return mock.SearchByFullTextFunc(ctx, query, limit)
}

// SearchByFullTextCalls gets all the calls that were made to SearchByFullText.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.SearchByFullTextCalls())
func (mock *DocumentChunkRepoerMock) SearchByFullTextCalls() []struct {
	Ctx   context.Context
	Query string
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Query string
		Limit int
	}
	mock.lockSearchByFullText.RLock()
	calls = mock.calls.SearchByFullText
	mock.lockSearchByFullText.RUnlock()
	return calls
}

// ShouldBeStored calls ShouldBeStoredFunc.
func (mock *DocumentChunkRepoerMock) ShouldBeStored(ctx context.Context, doc model.Document, chunk model.DocumentChunk) (bool, error) {
	if mock.ShouldBeStoredFunc == nil {
		panic("DocumentChunkRepoerMock.ShouldBeStoredFunc: method is nil but DocumentChunkRepoer.ShouldBeStored was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Doc   model.Document
		Chunk model.DocumentChunk
	}{
		Ctx:   ctx,
		Doc:   doc,
		Chunk: chunk,
	}
	mock.lockShouldBeStored.Lock()
	mock.calls.ShouldBeStored = append(mock.calls.ShouldBeStored, callInfo)
	mock.lockShouldBeStored.Unlock()
	return mock.ShouldBeStoredFunc(ctx, doc, chunk)
}

// ShouldBeStoredCalls gets all the calls that were made to ShouldBeStored.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.ShouldBeStoredCalls())
func (mock *DocumentChunkRepoerMock) ShouldBeStoredCalls() []struct {
	Ctx   context.Context
	Doc   model.Document
	Chunk model.DocumentChunk
} {
	var calls []struct {
		Ctx   context.Context
		Doc   model.Document
		Chunk model.DocumentChunk
	}
	mock.lockShouldBeStored.RLock()
	calls = mock.calls.ShouldBeStored
	mock.lockShouldBeStored.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *DocumentChunkRepoerMock) Update(ctx context.Context, chunk *model.DocumentChunk) error {
	if mock.UpdateFunc == nil {
		panic("DocumentChunkRepoerMock.UpdateFunc: method is nil but DocumentChunkRepoer.Update was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Chunk *model.DocumentChunk
	}{
		Ctx:   ctx,
		Chunk: chunk,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, chunk)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.UpdateCalls())
func (mock *DocumentChunkRepoerMock) UpdateCalls() []struct {
	Ctx   context.Context
	Chunk *model.DocumentChunk
} {
	var calls []struct {
		Ctx   context.Context
		Chunk *model.DocumentChunk
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// UpdateChunkTranslation calls UpdateChunkTranslationFunc.
func (mock *DocumentChunkRepoerMock) UpdateChunkTranslation(ctx context.Context, chunkID uuid.UUID, textTranslated string) error {
	if mock.UpdateChunkTranslationFunc == nil {
		panic("DocumentChunkRepoerMock.UpdateChunkTranslationFunc: method is nil but DocumentChunkRepoer.UpdateChunkTranslation was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		ChunkID        uuid.UUID
		TextTranslated string
	}{
		Ctx:            ctx,
		ChunkID:        chunkID,
		TextTranslated: textTranslated,
	}
	mock.lockUpdateChunkTranslation.Lock()
	mock.calls.UpdateChunkTranslation = append(mock.calls.UpdateChunkTranslation, callInfo)
	mock.lockUpdateChunkTranslation.Unlock()
	return mock.UpdateChunkTranslationFunc(ctx, chunkID, textTranslated)
}

// UpdateChunkTranslationCalls gets all the calls that were made to UpdateChunkTranslation.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.UpdateChunkTranslationCalls())
func (mock *DocumentChunkRepoerMock) UpdateChunkTranslationCalls() []struct {
	Ctx            context.Context
	ChunkID        uuid.UUID
	TextTranslated string
} {
	var calls []struct {
		Ctx            context.Context
		ChunkID        uuid.UUID
		TextTranslated string
	}
	mock.lockUpdateChunkTranslation.RLock()
	calls = mock.calls.UpdateChunkTranslation
	mock.lockUpdateChunkTranslation.RUnlock()
	return calls
}

// WithTx calls WithTxFunc.
func (mock *DocumentChunkRepoerMock) WithTx(ctx context.Context, fn func(data.DocumentChunkRepoer) error) error {
	if mock.WithTxFunc == nil {
		panic("DocumentChunkRepoerMock.WithTxFunc: method is nil but DocumentChunkRepoer.WithTx was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Fn  func(data.DocumentChunkRepoer) error
	}{
		Ctx: ctx,
		Fn:  fn,
	}
	mock.lockWithTx.Lock()
	mock.calls.WithTx = append(mock.calls.WithTx, callInfo)
	mock.lockWithTx.Unlock()
	return mock.WithTxFunc(ctx, fn)
}

// WithTxCalls gets all the calls that were made to WithTx.
// Check the length with:
//
//	len(mockedDocumentChunkRepoer.WithTxCalls())
func (mock *DocumentChunkRepoerMock) WithTxCalls() []struct {
	Ctx context.Context
	Fn  func(data.DocumentChunkRepoer) error
} {
	var calls []struct {
		Ctx context.Context
		Fn  func(data.DocumentChunkRepoer) error
	}
	mock.lockWithTx.RLock()
	calls = mock.calls.WithTx
	mock.lockWithTx.RUnlock()
	return calls
}
