// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: atomic_knowledge.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type CreateAtomicKnowledgeBatchParams struct {
	ID                   uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DocumentID           uuid.UUID
	DocumentChunkID      uuid.UUID
	TruthTier            int32
	Topics               []string
	Subject              string
	Predicate            string
	Object               string
	Note                 string
	MarkedAsInvalid      bool
	MarkedAsIrrelevant   bool
	Category             int32
	Language             int32
	SearchTextTranslated pgtype.Text
}

const getAtomicKnowledgeByID = `-- name: GetAtomicKnowledgeByID :one
SELECT id, created_at, updated_at, document_id, document_chunk_id, truth_tier, topics, subject, predicate, object, note, marked_as_invalid, marked_as_irrelevant, embedding, category, language, search_text_translated, fts_en, fts_fr FROM atomic_knowledge WHERE id = $1
`

func (q *Queries) GetAtomicKnowledgeByID(ctx context.Context, id uuid.UUID) (AtomicKnowledge, error) {
	row := q.db.QueryRow(ctx, getAtomicKnowledgeByID, id)
	var i AtomicKnowledge
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DocumentID,
		&i.DocumentChunkID,
		&i.TruthTier,
		&i.Topics,
		&i.Subject,
		&i.Predicate,
		&i.Object,
		&i.Note,
		&i.MarkedAsInvalid,
		&i.MarkedAsIrrelevant,
		&i.Embedding,
		&i.Category,
		&i.Language,
		&i.SearchTextTranslated,
		&i.FtsEn,
		&i.FtsFr,
	)
	return i, err
}

const listKnowledgeNeedingEmbedding = `-- name: ListKnowledgeNeedingEmbedding :many
SELECT id, created_at, updated_at, document_id, document_chunk_id, truth_tier, topics, subject, predicate, object, note, marked_as_invalid, marked_as_irrelevant, embedding, category, language, search_text_translated, fts_en, fts_fr FROM atomic_knowledge
WHERE document_id = $1 AND embedding IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListKnowledgeNeedingEmbedding(ctx context.Context, documentID uuid.UUID) ([]AtomicKnowledge, error) {
	rows, err := q.db.Query(ctx, listKnowledgeNeedingEmbedding, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AtomicKnowledge
	for rows.Next() {
		var i AtomicKnowledge
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DocumentID,
			&i.DocumentChunkID,
			&i.TruthTier,
			&i.Topics,
			&i.Subject,
			&i.Predicate,
			&i.Object,
			&i.Note,
			&i.MarkedAsInvalid,
			&i.MarkedAsIrrelevant,
			&i.Embedding,
			&i.Category,
			&i.Language,
			&i.SearchTextTranslated,
			&i.FtsEn,
			&i.FtsFr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAtomicKnowledgeEmbedding = `-- name: UpdateAtomicKnowledgeEmbedding :exec
UPDATE atomic_knowledge SET embedding = $2, updated_at = $3 WHERE id = $1
`

type UpdateAtomicKnowledgeEmbeddingParams struct {
	ID        uuid.UUID
	Embedding *pgvector_go.Vector
	UpdatedAt time.Time
}

func (q *Queries) UpdateAtomicKnowledgeEmbedding(ctx context.Context, arg UpdateAtomicKnowledgeEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateAtomicKnowledgeEmbedding, arg.ID, arg.Embedding, arg.UpdatedAt)
	return err
}
