// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateAtomicKnowledgeBatch implements pgx.CopyFromSource.
type iteratorForCreateAtomicKnowledgeBatch struct {
	rows                 []CreateAtomicKnowledgeBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateAtomicKnowledgeBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateAtomicKnowledgeBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
		r.rows[0].DocumentID,
		r.rows[0].DocumentChunkID,
		r.rows[0].TruthTier,
		r.rows[0].Topics,
		r.rows[0].Subject,
		r.rows[0].Predicate,
		r.rows[0].Object,
		r.rows[0].Note,
		r.rows[0].MarkedAsInvalid,
		r.rows[0].MarkedAsIrrelevant,
		r.rows[0].Category,
		r.rows[0].Language,
		r.rows[0].SearchTextTranslated,
	}, nil
}

func (r iteratorForCreateAtomicKnowledgeBatch) Err() error {
	return nil
}

func (q *Queries) CreateAtomicKnowledgeBatch(ctx context.Context, arg []CreateAtomicKnowledgeBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"atomic_knowledge"}, []string{"id", "created_at", "updated_at", "document_id", "document_chunk_id", "truth_tier", "topics", "subject", "predicate", "object", "note", "marked_as_invalid", "marked_as_irrelevant", "category", "language", "search_text_translated"}, &iteratorForCreateAtomicKnowledgeBatch{rows: arg})
}

// iteratorForCreateDocumentChunksBatch implements pgx.CopyFromSource.
type iteratorForCreateDocumentChunksBatch struct {
	rows                 []CreateDocumentChunksBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateDocumentChunksBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateDocumentChunksBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
		r.rows[0].DocumentID,
		r.rows[0].SequenceNumber,
		r.rows[0].Topics,
		r.rows[0].FactualityScore,
		r.rows[0].Text,
		r.rows[0].Page,
		r.rows[0].Chapter,
		r.rows[0].LayoutType,
		r.rows[0].BoundingBox,
		r.rows[0].AssetUrl,
		r.rows[0].Language,
		r.rows[0].TextTranslated,
	}, nil
}

func (r iteratorForCreateDocumentChunksBatch) Err() error {
	return nil
}

func (q *Queries) CreateDocumentChunksBatch(ctx context.Context, arg []CreateDocumentChunksBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"document_chunks"}, []string{"id", "created_at", "updated_at", "document_id", "sequence_number", "topics", "factuality_score", "text", "page", "chapter", "layout_type", "bounding_box", "asset_url", "language", "text_translated"}, &iteratorForCreateDocumentChunksBatch{rows: arg})
}
