// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDocuments = `-- name: CountDocuments :one
SELECT count(*) FROM documents
`

func (q *Queries) CountDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDocuments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    id, created_at, modified_at, ingested_at, file_key, sha256,
    title, filename, filetype, filesize, page_count, publisher_name, publication_year,
    language
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, created_at, modified_at, ingested_at, file_key, sha256, title, filename, filetype, filesize, page_count, publisher_name, publication_year, language
`

type CreateDocumentParams struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	ModifiedAt      time.Time
	IngestedAt      pgtype.Timestamptz
	FileKey         string
	Sha256          string
	Title           string
	Filename        string
	Filetype        string
	Filesize        int64
	PageCount       int32
	PublisherName   string
	PublicationYear int32
	Language        int32
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.CreatedAt,
		arg.ModifiedAt,
		arg.IngestedAt,
		arg.FileKey,
		arg.Sha256,
		arg.Title,
		arg.Filename,
		arg.Filetype,
		arg.Filesize,
		arg.PageCount,
		arg.PublisherName,
		arg.PublicationYear,
		arg.Language,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.IngestedAt,
		&i.FileKey,
		&i.Sha256,
		&i.Title,
		&i.Filename,
		&i.Filetype,
		&i.Filesize,
		&i.PageCount,
		&i.PublisherName,
		&i.PublicationYear,
		&i.Language,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, created_at, modified_at, ingested_at, file_key, sha256, title, filename, filetype, filesize, page_count, publisher_name, publication_year, language FROM documents WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.IngestedAt,
		&i.FileKey,
		&i.Sha256,
		&i.Title,
		&i.Filename,
		&i.Filetype,
		&i.Filesize,
		&i.PageCount,
		&i.PublisherName,
		&i.PublicationYear,
		&i.Language,
	)
	return i, err
}

const getDocumentBySHA256 = `-- name: GetDocumentBySHA256 :one
SELECT id, created_at, modified_at, ingested_at, file_key, sha256, title, filename, filetype, filesize, page_count, publisher_name, publication_year, language FROM documents WHERE sha256 = $1
`

func (q *Queries) GetDocumentBySHA256(ctx context.Context, sha256 string) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentBySHA256, sha256)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.IngestedAt,
		&i.FileKey,
		&i.Sha256,
		&i.Title,
		&i.Filename,
		&i.Filetype,
		&i.Filesize,
		&i.PageCount,
		&i.PublisherName,
		&i.PublicationYear,
		&i.Language,
	)
	return i, err
}

const paginateDocuments = `-- name: PaginateDocuments :many
SELECT id, created_at, modified_at, ingested_at, file_key, sha256, title, filename, filetype, filesize, page_count, publisher_name, publication_year, language FROM documents ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type PaginateDocumentsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) PaginateDocuments(ctx context.Context, arg PaginateDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, paginateDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.IngestedAt,
			&i.FileKey,
			&i.Sha256,
			&i.Title,
			&i.Filename,
			&i.Filetype,
			&i.Filesize,
			&i.PageCount,
			&i.PublisherName,
			&i.PublicationYear,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents SET
    modified_at = $2,
    ingested_at = $3,
    file_key = $4,
    sha256 = $5,
    title = $6,
    filename = $7,
    filetype = $8,
    filesize = $9,
    page_count = $10,
    publisher_name = $11,
    publication_year = $12,
    language = $13
WHERE id = $1
RETURNING id, created_at, modified_at, ingested_at, file_key, sha256, title, filename, filetype, filesize, page_count, publisher_name, publication_year, language
`

type UpdateDocumentParams struct {
	ID              uuid.UUID
	ModifiedAt      time.Time
	IngestedAt      pgtype.Timestamptz
	FileKey         string
	Sha256          string
	Title           string
	Filename        string
	Filetype        string
	Filesize        int64
	PageCount       int32
	PublisherName   string
	PublicationYear int32
	Language        int32
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.ID,
		arg.ModifiedAt,
		arg.IngestedAt,
		arg.FileKey,
		arg.Sha256,
		arg.Title,
		arg.Filename,
		arg.Filetype,
		arg.Filesize,
		arg.PageCount,
		arg.PublisherName,
		arg.PublicationYear,
		arg.Language,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.IngestedAt,
		&i.FileKey,
		&i.Sha256,
		&i.Title,
		&i.Filename,
		&i.Filetype,
		&i.Filesize,
		&i.PageCount,
		&i.PublisherName,
		&i.PublicationYear,
		&i.Language,
	)
	return i, err
}
