// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_chunk.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type CreateDocumentChunksBatchParams struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DocumentID      uuid.UUID
	SequenceNumber  int32
	Topics          []string
	FactualityScore float64
	Text            string
	Page            int32
	Chapter         string
	LayoutType      string
	BoundingBox     []float64
	AssetUrl        string
	Language        int32
	TextTranslated  pgtype.Text
}

const getDocumentChunkByID = `-- name: GetDocumentChunkByID :one
SELECT id, created_at, updated_at, document_id, sequence_number, topics, factuality_score, text, page, chapter, layout_type, bounding_box, asset_url, embedding, knowledge_extracted_at, language, text_translated, text_fts_en, text_fts_fr FROM document_chunks WHERE id = $1
`

func (q *Queries) GetDocumentChunkByID(ctx context.Context, id uuid.UUID) (DocumentChunk, error) {
	row := q.db.QueryRow(ctx, getDocumentChunkByID, id)
	var i DocumentChunk
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DocumentID,
		&i.SequenceNumber,
		&i.Topics,
		&i.FactualityScore,
		&i.Text,
		&i.Page,
		&i.Chapter,
		&i.LayoutType,
		&i.BoundingBox,
		&i.AssetUrl,
		&i.Embedding,
		&i.KnowledgeExtractedAt,
		&i.Language,
		&i.TextTranslated,
		&i.TextFtsEn,
		&i.TextFtsFr,
	)
	return i, err
}

const listChunksNeedingEmbedding = `-- name: ListChunksNeedingEmbedding :many
SELECT id, created_at, updated_at, document_id, sequence_number, topics, factuality_score, text, page, chapter, layout_type, bounding_box, asset_url, embedding, knowledge_extracted_at, language, text_translated, text_fts_en, text_fts_fr FROM document_chunks
WHERE document_id = $1 AND text != '' AND embedding IS NULL
ORDER BY sequence_number ASC
`

func (q *Queries) ListChunksNeedingEmbedding(ctx context.Context, documentID uuid.UUID) ([]DocumentChunk, error) {
	rows, err := q.db.Query(ctx, listChunksNeedingEmbedding, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentChunk
	for rows.Next() {
		var i DocumentChunk
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DocumentID,
			&i.SequenceNumber,
			&i.Topics,
			&i.FactualityScore,
			&i.Text,
			&i.Page,
			&i.Chapter,
			&i.LayoutType,
			&i.BoundingBox,
			&i.AssetUrl,
			&i.Embedding,
			&i.KnowledgeExtractedAt,
			&i.Language,
			&i.TextTranslated,
			&i.TextFtsEn,
			&i.TextFtsFr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChunksNeedingKnowledgeExtraction = `-- name: ListChunksNeedingKnowledgeExtraction :many
SELECT id, created_at, updated_at, document_id, sequence_number, topics, factuality_score, text, page, chapter, layout_type, bounding_box, asset_url, embedding, knowledge_extracted_at, language, text_translated, text_fts_en, text_fts_fr FROM document_chunks
WHERE document_id = $1 AND text != '' AND knowledge_extracted_at IS NULL
ORDER BY sequence_number ASC
`

func (q *Queries) ListChunksNeedingKnowledgeExtraction(ctx context.Context, documentID uuid.UUID) ([]DocumentChunk, error) {
	rows, err := q.db.Query(ctx, listChunksNeedingKnowledgeExtraction, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentChunk
	for rows.Next() {
		var i DocumentChunk
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DocumentID,
			&i.SequenceNumber,
			&i.Topics,
			&i.FactualityScore,
			&i.Text,
			&i.Page,
			&i.Chapter,
			&i.LayoutType,
			&i.BoundingBox,
			&i.AssetUrl,
			&i.Embedding,
			&i.KnowledgeExtractedAt,
			&i.Language,
			&i.TextTranslated,
			&i.TextFtsEn,
			&i.TextFtsFr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChunksNeedingTranslation = `-- name: ListChunksNeedingTranslation :many
SELECT id, created_at, updated_at, document_id, sequence_number, topics, factuality_score, text, page, chapter, layout_type, bounding_box, asset_url, embedding, knowledge_extracted_at, language, text_translated, text_fts_en, text_fts_fr FROM document_chunks
WHERE document_id = $1 AND text != '' AND text_translated IS NULL
ORDER BY sequence_number ASC
`

func (q *Queries) ListChunksNeedingTranslation(ctx context.Context, documentID uuid.UUID) ([]DocumentChunk, error) {
	rows, err := q.db.Query(ctx, listChunksNeedingTranslation, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentChunk
	for rows.Next() {
		var i DocumentChunk
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DocumentID,
			&i.SequenceNumber,
			&i.Topics,
			&i.FactualityScore,
			&i.Text,
			&i.Page,
			&i.Chapter,
			&i.LayoutType,
			&i.BoundingBox,
			&i.AssetUrl,
			&i.Embedding,
			&i.KnowledgeExtractedAt,
			&i.Language,
			&i.TextTranslated,
			&i.TextFtsEn,
			&i.TextFtsFr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentChunksByDocumentID = `-- name: ListDocumentChunksByDocumentID :many
SELECT id, created_at, updated_at, document_id, sequence_number, topics, factuality_score, text, page, chapter, layout_type, bounding_box, asset_url, embedding, knowledge_extracted_at, language, text_translated, text_fts_en, text_fts_fr FROM document_chunks WHERE document_id = $1 ORDER BY sequence_number ASC
`

func (q *Queries) ListDocumentChunksByDocumentID(ctx context.Context, documentID uuid.UUID) ([]DocumentChunk, error) {
	rows, err := q.db.Query(ctx, listDocumentChunksByDocumentID, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentChunk
	for rows.Next() {
		var i DocumentChunk
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DocumentID,
			&i.SequenceNumber,
			&i.Topics,
			&i.FactualityScore,
			&i.Text,
			&i.Page,
			&i.Chapter,
			&i.LayoutType,
			&i.BoundingBox,
			&i.AssetUrl,
			&i.Embedding,
			&i.KnowledgeExtractedAt,
			&i.Language,
			&i.TextTranslated,
			&i.TextFtsEn,
			&i.TextFtsFr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentIDsNeedingTranslation = `-- name: ListDocumentIDsNeedingTranslation :many
SELECT DISTINCT document_id FROM document_chunks
WHERE text != '' AND text_translated IS NULL
`

func (q *Queries) ListDocumentIDsNeedingTranslation(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDocumentIDsNeedingTranslation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var document_id uuid.UUID
		if err := rows.Scan(&document_id); err != nil {
			return nil, err
		}
		items = append(items, document_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChunkKnowledgeExtracted = `-- name: MarkChunkKnowledgeExtracted :exec
UPDATE document_chunks SET knowledge_extracted_at = now() WHERE id = $1
`

func (q *Queries) MarkChunkKnowledgeExtracted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markChunkKnowledgeExtracted, id)
	return err
}

const updateChunkTranslation = `-- name: UpdateChunkTranslation :exec
UPDATE document_chunks SET text_translated = $2, updated_at = $3 WHERE id = $1
`

type UpdateChunkTranslationParams struct {
	ID             uuid.UUID
	TextTranslated pgtype.Text
	UpdatedAt      time.Time
}

func (q *Queries) UpdateChunkTranslation(ctx context.Context, arg UpdateChunkTranslationParams) error {
	_, err := q.db.Exec(ctx, updateChunkTranslation, arg.ID, arg.TextTranslated, arg.UpdatedAt)
	return err
}

const updateDocumentChunk = `-- name: UpdateDocumentChunk :one
UPDATE document_chunks SET
    updated_at = $2,
    topics = $3,
    factuality_score = $4,
    text = $5,
    chapter = $6,
    asset_url = $7,
    embedding = $8
WHERE id = $1
RETURNING id, created_at, updated_at, document_id, sequence_number, topics, factuality_score, text, page, chapter, layout_type, bounding_box, asset_url, embedding, knowledge_extracted_at, language, text_translated, text_fts_en, text_fts_fr
`

type UpdateDocumentChunkParams struct {
	ID              uuid.UUID
	UpdatedAt       time.Time
	Topics          []string
	FactualityScore float64
	Text            string
	Chapter         string
	AssetUrl        string
	Embedding       *pgvector_go.Vector
}

func (q *Queries) UpdateDocumentChunk(ctx context.Context, arg UpdateDocumentChunkParams) (DocumentChunk, error) {
	row := q.db.QueryRow(ctx, updateDocumentChunk,
		arg.ID,
		arg.UpdatedAt,
		arg.Topics,
		arg.FactualityScore,
		arg.Text,
		arg.Chapter,
		arg.AssetUrl,
		arg.Embedding,
	)
	var i DocumentChunk
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DocumentID,
		&i.SequenceNumber,
		&i.Topics,
		&i.FactualityScore,
		&i.Text,
		&i.Page,
		&i.Chapter,
		&i.LayoutType,
		&i.BoundingBox,
		&i.AssetUrl,
		&i.Embedding,
		&i.KnowledgeExtractedAt,
		&i.Language,
		&i.TextTranslated,
		&i.TextFtsEn,
		&i.TextFtsFr,
	)
	return i, err
}
