// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type AtomicKnowledge struct {
	ID                   uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DocumentID           uuid.UUID
	DocumentChunkID      uuid.UUID
	TruthTier            int32
	Topics               []string
	Subject              string
	Predicate            string
	Object               string
	Note                 string
	MarkedAsInvalid      bool
	MarkedAsIrrelevant   bool
	Embedding            *pgvector_go.Vector
	Category             int32
	Language             int32
	SearchTextTranslated pgtype.Text
	FtsEn                interface{}
	FtsFr                interface{}
}

type Document struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	ModifiedAt      time.Time
	IngestedAt      pgtype.Timestamptz
	FileKey         string
	Sha256          string
	Title           string
	Filename        string
	Filetype        string
	Filesize        int64
	PageCount       int32
	PublisherName   string
	PublicationYear int32
	Language        int32
}

type DocumentChunk struct {
	ID                   uuid.UUID
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DocumentID           uuid.UUID
	SequenceNumber       int32
	Topics               []string
	FactualityScore      float64
	Text                 string
	Page                 int32
	Chapter              string
	LayoutType           string
	BoundingBox          []float64
	AssetUrl             string
	Embedding            *pgvector_go.Vector
	KnowledgeExtractedAt pgtype.Timestamptz
	Language             int32
	TextTranslated       pgtype.Text
	TextFtsEn            interface{}
	TextFtsFr            interface{}
}

type User struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
	Role         int16
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Video struct {
	ID                uuid.UUID
	VideoUrl          string
	AuthorUsername    string
	AuthorProfileUrl  string
	Caption           pgtype.Text
	PlayCount         pgtype.Int8
	LikeCount         pgtype.Int8
	ThumbnailUrl      string
	LocationCreated   pgtype.Text
	VideoCreatedAt    pgtype.Timestamptz
	TranscriptionText pgtype.Text
	Hashtags          []string
	VideoType         string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
