// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mockrepo

import (
	"context"
	"github.com/google/uuid"
	"github.com/kairosedubf/wobsongo/data"
	"github.com/kairosedubf/wobsongo/dto"
	"github.com/kairosedubf/wobsongo/model"
	"github.com/kairosedubf/wobsongo/queue"
	"sync"
)

// Ensure, that DocumentRepoerMock does implement data.DocumentRepoer.
// If this is not the case, regenerate this file with moq.
var _ data.DocumentRepoer = &DocumentRepoerMock{}

// DocumentRepoerMock is a mock implementation of data.DocumentRepoer.
//
//	func TestSomethingThatUsesDocumentRepoer(t *testing.T) {
//
//		// make and configure a mocked data.DocumentRepoer
//		mockedDocumentRepoer := &DocumentRepoerMock{
//			CreateFunc: func(ctx context.Context, entity *model.Document) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the Delete method")
//			},
//			EnqueueFunc: func(ctx context.Context, payload queue.BackgroundJob) error {
//				panic("mock out the Enqueue method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*model.Document, error) {
//				panic("mock out the GetByID method")
//			},
//			GetBySHA256Func: func(ctx context.Context, sha256 string) (*model.Document, error) {
//				panic("mock out the GetBySHA256 method")
//			},
//			PaginateFunc: func(ctx context.Context, q data.SupportsPagination) (*dto.PaginationResults[model.Document], error) {
//				panic("mock out the Paginate method")
//			},
//			UpdateFunc: func(ctx context.Context, entity *model.Document) error {
//				panic("mock out the Update method")
//			},
//			WithTxFunc: func(ctx context.Context, fn func(data.DocumentRepoer) error) error {
//				panic("mock out the WithTx method")
//			},
//		}
//
//		// use mockedDocumentRepoer in code that requires data.DocumentRepoer
//		// and then make assertions.
//
//	}
type DocumentRepoerMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, entity *model.Document) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id uuid.UUID) error

	// EnqueueFunc mocks the Enqueue method.
	EnqueueFunc func(ctx context.Context, payload queue.BackgroundJob) error

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*model.Document, error)

	// GetBySHA256Func mocks the GetBySHA256 method.
	GetBySHA256Func func(ctx context.Context, sha256 string) (*model.Document, error)

	// PaginateFunc mocks the Paginate method.
	PaginateFunc func(ctx context.Context, q data.SupportsPagination) (*dto.PaginationResults[model.Document], error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, entity *model.Document) error

	// WithTxFunc mocks the WithTx method.
	WithTxFunc func(ctx context.Context, fn func(data.DocumentRepoer) error) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity *model.Document
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// Enqueue holds details about calls to the Enqueue method.
		Enqueue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Payload is the payload argument value.
			Payload queue.BackgroundJob
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetBySHA256 holds details about calls to the GetBySHA256 method.
		GetBySHA256 []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Sha256 is the sha256 argument value.
			Sha256 string
		}
		// Paginate holds details about calls to the Paginate method.
		Paginate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q data.SupportsPagination
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity *model.Document
		}
		// WithTx holds details about calls to the WithTx method.
		WithTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fn is the fn argument value.
			Fn func(data.DocumentRepoer) error
		}
	}
	lockCreate      sync.RWMutex
	lockDelete      sync.RWMutex
	lockEnqueue     sync.RWMutex
	lockGetByID     sync.RWMutex
	lockGetBySHA256 sync.RWMutex
	lockPaginate    sync.RWMutex
	lockUpdate      sync.RWMutex
	lockWithTx      sync.RWMutex
}

// Create calls CreateFunc.
func (mock *DocumentRepoerMock) Create(ctx context.Context, entity *model.Document) error {
	if mock.CreateFunc == nil {
		panic("DocumentRepoerMock.CreateFunc: method is nil but DocumentRepoer.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity *model.Document
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, entity)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedDocumentRepoer.CreateCalls())
func (mock *DocumentRepoerMock) CreateCalls() []struct {
	Ctx    context.Context
	Entity *model.Document
} {
	var calls []struct {
		Ctx    context.Context
		Entity *model.Document
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *DocumentRepoerMock) Delete(ctx context.Context, id uuid.UUID) error {
	if mock.DeleteFunc == nil {
		panic("DocumentRepoerMock.DeleteFunc: method is nil but DocumentRepoer.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedDocumentRepoer.DeleteCalls())
func (mock *DocumentRepoerMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Enqueue calls EnqueueFunc.
func (mock *DocumentRepoerMock) Enqueue(ctx context.Context, payload queue.BackgroundJob) error {
	if mock.EnqueueFunc == nil {
		panic("DocumentRepoerMock.EnqueueFunc: method is nil but DocumentRepoer.Enqueue was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Payload queue.BackgroundJob
	}{
		Ctx:     ctx,
		Payload: payload,
	}
	mock.lockEnqueue.Lock()
	mock.calls.Enqueue = append(mock.calls.Enqueue, callInfo)
	mock.lockEnqueue.Unlock()
	return mock.EnqueueFunc(ctx, payload)
}

// EnqueueCalls gets all the calls that were made to Enqueue.
// Check the length with:
//
//	len(mockedDocumentRepoer.EnqueueCalls())
func (mock *DocumentRepoerMock) EnqueueCalls() []struct {
	Ctx     context.Context
	Payload queue.BackgroundJob
} {
	var calls []struct {
		Ctx     context.Context
		Payload queue.BackgroundJob
	}
	mock.lockEnqueue.RLock()
	calls = mock.calls.Enqueue
	mock.lockEnqueue.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *DocumentRepoerMock) GetByID(ctx context.Context, id uuid.UUID) (*model.Document, error) {
	if mock.GetByIDFunc == nil {
		panic("DocumentRepoerMock.GetByIDFunc: method is nil but DocumentRepoer.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedDocumentRepoer.GetByIDCalls())
func (mock *DocumentRepoerMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetBySHA256 calls GetBySHA256Func.
func (mock *DocumentRepoerMock) GetBySHA256(ctx context.Context, sha256 string) (*model.Document, error) {
	if mock.GetBySHA256Func == nil {
		panic("DocumentRepoerMock.GetBySHA256Func: method is nil but DocumentRepoer.GetBySHA256 was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Sha256 string
	}{
		Ctx:    ctx,
		Sha256: sha256,
	}
	mock.lockGetBySHA256.Lock()
	mock.calls.GetBySHA256 = append(mock.calls.GetBySHA256, callInfo)
	mock.lockGetBySHA256.Unlock()
	return mock.GetBySHA256Func(ctx, sha256)
}

// GetBySHA256Calls gets all the calls that were made to GetBySHA256.
// Check the length with:
//
//	len(mockedDocumentRepoer.GetBySHA256Calls())
func (mock *DocumentRepoerMock) GetBySHA256Calls() []struct {
	Ctx    context.Context
	Sha256 string
} {
	var calls []struct {
		Ctx    context.Context
		Sha256 string
	}
	mock.lockGetBySHA256.RLock()
	calls = mock.calls.GetBySHA256
	mock.lockGetBySHA256.RUnlock()
	return calls
}

// Paginate calls PaginateFunc.
func (mock *DocumentRepoerMock) Paginate(ctx context.Context, q data.SupportsPagination) (*dto.PaginationResults[model.Document], error) {
	if mock.PaginateFunc == nil {
		panic("DocumentRepoerMock.PaginateFunc: method is nil but DocumentRepoer.Paginate was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Q   data.SupportsPagination
	}{
		Ctx: ctx,
		Q:   q,
	}
	mock.lockPaginate.Lock()
	mock.calls.Paginate = append(mock.calls.Paginate, callInfo)
	mock.lockPaginate.Unlock()
	return mock.PaginateFunc(ctx, q)
}

// PaginateCalls gets all the calls that were made to Paginate.
// Check the length with:
//
//	len(mockedDocumentRepoer.PaginateCalls())
func (mock *DocumentRepoerMock) PaginateCalls() []struct {
	Ctx context.Context
	Q   data.SupportsPagination
} {
	var calls []struct {
		Ctx context.Context
		Q   data.SupportsPagination
	}
	mock.lockPaginate.RLock()
	calls = mock.calls.Paginate
	mock.lockPaginate.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *DocumentRepoerMock) Update(ctx context.Context, entity *model.Document) error {
	if mock.UpdateFunc == nil {
		panic("DocumentRepoerMock.UpdateFunc: method is nil but DocumentRepoer.Update was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity *model.Document
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, entity)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedDocumentRepoer.UpdateCalls())
func (mock *DocumentRepoerMock) UpdateCalls() []struct {
	Ctx    context.Context
	Entity *model.Document
} {
	var calls []struct {
		Ctx    context.Context
		Entity *model.Document
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// WithTx calls WithTxFunc.
func (mock *DocumentRepoerMock) WithTx(ctx context.Context, fn func(data.DocumentRepoer) error) error {
	if mock.WithTxFunc == nil {
		panic("DocumentRepoerMock.WithTxFunc: method is nil but DocumentRepoer.WithTx was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Fn  func(data.DocumentRepoer) error
	}{
		Ctx: ctx,
		Fn:  fn,
	}
	mock.lockWithTx.Lock()
	mock.calls.WithTx = append(mock.calls.WithTx, callInfo)
	mock.lockWithTx.Unlock()
	return mock.WithTxFunc(ctx, fn)
}

// WithTxCalls gets all the calls that were made to WithTx.
// Check the length with:
//
//	len(mockedDocumentRepoer.WithTxCalls())
func (mock *DocumentRepoerMock) WithTxCalls() []struct {
	Ctx context.Context
	Fn  func(data.DocumentRepoer) error
} {
	var calls []struct {
		Ctx context.Context
		Fn  func(data.DocumentRepoer) error
	}
	mock.lockWithTx.RLock()
	calls = mock.calls.WithTx
	mock.lockWithTx.RUnlock()
	return calls
}
