// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mockrepo

import (
	"context"
	"github.com/google/uuid"
	"github.com/kairosedubf/wobsongo/data"
	"github.com/kairosedubf/wobsongo/model"
	"sync"
)

// Ensure, that UserRepoerMock does implement data.UserRepoer.
// If this is not the case, regenerate this file with moq.
var _ data.UserRepoer = &UserRepoerMock{}

// UserRepoerMock is a mock implementation of data.UserRepoer.
//
//	func TestSomethingThatUsesUserRepoer(t *testing.T) {
//
//		// make and configure a mocked data.UserRepoer
//		mockedUserRepoer := &UserRepoerMock{
//			CreateFunc: func(ctx context.Context, user *model.User) error {
//				panic("mock out the Create method")
//			},
//			GetByEmailFunc: func(ctx context.Context, email string) (*model.User, error) {
//				panic("mock out the GetByEmail method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*model.User, error) {
//				panic("mock out the GetByID method")
//			},
//			UpdateRoleFunc: func(ctx context.Context, id uuid.UUID, role model.UserRole) (*model.User, error) {
//				panic("mock out the UpdateRole method")
//			},
//		}
//
//		// use mockedUserRepoer in code that requires data.UserRepoer
//		// and then make assertions.
//
//	}
type UserRepoerMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, user *model.User) error

	// GetByEmailFunc mocks the GetByEmail method.
	GetByEmailFunc func(ctx context.Context, email string) (*model.User, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*model.User, error)

	// UpdateRoleFunc mocks the UpdateRole method.
	UpdateRoleFunc func(ctx context.Context, id uuid.UUID, role model.UserRole) (*model.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *model.User
		}
		// GetByEmail holds details about calls to the GetByEmail method.
		GetByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// UpdateRole holds details about calls to the UpdateRole method.
		UpdateRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// Role is the role argument value.
			Role model.UserRole
		}
	}
	lockCreate     sync.RWMutex
	lockGetByEmail sync.RWMutex
	lockGetByID    sync.RWMutex
	lockUpdateRole sync.RWMutex
}

// Create calls CreateFunc.
func (mock *UserRepoerMock) Create(ctx context.Context, user *model.User) error {
	if mock.CreateFunc == nil {
		panic("UserRepoerMock.CreateFunc: method is nil but UserRepoer.Create was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User *model.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, user)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUserRepoer.CreateCalls())
func (mock *UserRepoerMock) CreateCalls() []struct {
	Ctx  context.Context
	User *model.User
} {
	var calls []struct {
		Ctx  context.Context
		User *model.User
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// GetByEmail calls GetByEmailFunc.
func (mock *UserRepoerMock) GetByEmail(ctx context.Context, email string) (*model.User, error) {
	if mock.GetByEmailFunc == nil {
		panic("UserRepoerMock.GetByEmailFunc: method is nil but UserRepoer.GetByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockGetByEmail.Lock()
	mock.calls.GetByEmail = append(mock.calls.GetByEmail, callInfo)
	mock.lockGetByEmail.Unlock()
	return mock.GetByEmailFunc(ctx, email)
}

// GetByEmailCalls gets all the calls that were made to GetByEmail.
// Check the length with:
//
//	len(mockedUserRepoer.GetByEmailCalls())
func (mock *UserRepoerMock) GetByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockGetByEmail.RLock()
	calls = mock.calls.GetByEmail
	mock.lockGetByEmail.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *UserRepoerMock) GetByID(ctx context.Context, id uuid.UUID) (*model.User, error) {
	if mock.GetByIDFunc == nil {
		panic("UserRepoerMock.GetByIDFunc: method is nil but UserRepoer.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedUserRepoer.GetByIDCalls())
func (mock *UserRepoerMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// UpdateRole calls UpdateRoleFunc.
func (mock *UserRepoerMock) UpdateRole(ctx context.Context, id uuid.UUID, role model.UserRole) (*model.User, error) {
	if mock.UpdateRoleFunc == nil {
		panic("UserRepoerMock.UpdateRoleFunc: method is nil but UserRepoer.UpdateRole was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		ID   uuid.UUID
		Role model.UserRole
	}{
		Ctx:  ctx,
		ID:   id,
		Role: role,
	}
	mock.lockUpdateRole.Lock()
	mock.calls.UpdateRole = append(mock.calls.UpdateRole, callInfo)
	mock.lockUpdateRole.Unlock()
	return mock.UpdateRoleFunc(ctx, id, role)
}

// UpdateRoleCalls gets all the calls that were made to UpdateRole.
// Check the length with:
//
//	len(mockedUserRepoer.UpdateRoleCalls())
func (mock *UserRepoerMock) UpdateRoleCalls() []struct {
	Ctx  context.Context
	ID   uuid.UUID
	Role model.UserRole
} {
	var calls []struct {
		Ctx  context.Context
		ID   uuid.UUID
		Role model.UserRole
	}
	mock.lockUpdateRole.RLock()
	calls = mock.calls.UpdateRole
	mock.lockUpdateRole.RUnlock()
	return calls
}
